FROM nginx:1.15.0-alpine
# 1.25.2-alpine

# Replace default.conf with nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# RUN chown -R www-data:www-data /var/www
# Create html directory then a index.php file
RUN mkdir /var/www/html -p && \
    touch /var/www/html/index.php