version: '3'

services:

  laravel:
    build:
      context: ./php-laravel
      dockerfile: Dockerfile.prod
    image: bhabermann/php8-laravel:prod
    container_name: laravel
    networks:
      - laravel-network

  nginx:
    build:
      context: ./php-laravel
      dockerfile: Dockerfile.nginx
    image: bhabermann/php8-laravel:nginx
    container_name: laravel-nginx
    networks:
      - laravel-network
    ports:
      - "8080:80"

networks:
  laravel-network:
    driver: bridge
