version: '3'

services:

  nodeapp:
    build:
      context: node-express
    entrypoint: dockerize -wait tcp://nodedb:3306 docker-entrypoint.sh
    command: node index.js
    container_name: nodeapp
    networks:
      - node-network
    volumes:
      - ./node-express:/usr/src/app
    tty: true
    depends_on:
      - nodedb

  nodedb:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: nodedb
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - node-network

  nodenginx:
    build:
      context: nginx-reverse-proxy
    container_name: nodenginx
    networks:
      - node-network
    ports:
      - "80:80"
    depends_on:
      - nodeapp

networks:
  node-network:
    driver: bridge
    name: node-network
